# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 461bcf391d472983656054018d1e31cc4d63a3af410ce69cf76506308b5469c376993dda2edec13feb38070d8c7e6a66146b242bd2dc2501c5e4e2835663806f

test:
  secret_key_base: 73273137eb68ac837cac2e6121f0793210fb3dc5ea7fdcdefb56942fe8ea4084f9fc8e360dc4d5b01fde99d54760d3059a19b3c4b07899e63c90df52692005e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
